apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Ingress HTTP/HTTPS apontando para o Service da aplicacao backend
  name: {SERVICE_NAME}
  labels:
    app: {SERVICE_NAME}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-rate-limit@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        # Host publico da sua API (subdominio api do SEU dominio)
        # Ex.: se DOMAIN={DOMAIN} -> api.{DOMAIN}
        - api.{DOMAIN}
      # Secret TLS criado pelo cert-manager para este host
      secretName: api-{DOMAIN}-tls
  rules:
    - host: api.{DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {SERVICE_NAME}
                port:
                  number: 80
