apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Ingress HTTP/HTTPS apontando para o Service da aplicacao backend
  name: myservice-api
  labels:
    app: myservice-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-rate-limit@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        # Host publico da sua API (subdominio api do SEU dominio)
        # Ex.: se DOMAIN=seudominio.com -> api.seudominio.com
        - api.seudominio.com
      # Secret TLS criado pelo cert-manager para este host
      secretName: api-seudominio-com-tls
  rules:
    - host: api.seudominio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myservice-api
                port:
                  number: 80
