apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Ingress HTTP/HTTPS do frontend
  name: {FRONT_NAME}
  labels:
    app: {FRONT_NAME}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-rate-limit@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        # Host publico do frontend (subdominio app do SEU dominio)
        # Ex.: se DOMAIN={BASE_DOMAIN} -> app.{BASE_DOMAIN}
        - app.{BASE_DOMAIN}
      secretName: app-{BASE_DOMAIN}-tls
  rules:
    - host: app.{BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {FRONT_NAME}
                port:
                  number: 80
